services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app-web
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    # web does NOT depend on worker/tracker
    # because Next.js can start independently

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app-worker
    command: npm run worker
    env_file:
      - .env.docker
    depends_on:
      - web  # ✅ worker depends on web for API routes

  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app-tracker
    command: npm run tracker
    env_file:
      - .env.docker
    depends_on:
      - web  # ✅ tracker depends on web for API routes
