import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export default function RootLayout({ children }) {
  // ⚠️ Skip ClerkProvider during build if env var missing
  if (!publishableKey) {
    console.warn(
      "⚠️ Missing Clerk publishable key during build — rendering without ClerkProvider"
    );
    return (
      <html lang="en">
        <head>
          <title>TradeX</title>
          <meta name="description" content="Generated by create next app" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </body>
      </html>
    );
  }

  // ✅ Normal runtime case (Clerk key is present)
  return (
    <ClerkProvider publishableKey={publishableKey}>
      <html lang="en">
        <head>
          <title>TradeX</title>
          <meta name="description" content="Generated by create next app" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </body>
      </html>
    </ClerkProvider>
  );
}
